### ISSUE TITLE
Błędy podczas uruchamiania projektu

### ISSUE THREAD

**Issue by karolgebert** [wisien92/ArenaGame#7]
`Failed to load map!
../../../../../../Users/doop/Documents/Unreal Projects/ArenaGame/Content/Maps/Test.umap appears to be an asset file.`

![blad_1](https://user-images.githubusercontent.com/3704837/42841474-7a4b8b30-8a0a-11e8-8d01-374ee1eb3dff.PNG)

**Comment by karolgebert** [comment]
![blad_2](https://user-images.githubusercontent.com/3704837/42841568-c3db82a0-8a0a-11e8-89b1-37f362ccae28.PNG)

**Comment by karolgebert** [comment]
Takie błędy mam jak odpalam edytor. Najpierw ten dotyczący HUD, później ten z mapą. Dodatkowo nie mam w Content browser plików. Usuwałem już cache, ale to nic nie pomogło. Pliki znajdują się w eksploratorze systemowym, ale nie w edytorze ;-/

**Comment by wisien92** [comment]
Już pisałem w prywatnej wiadomości ale wrzucę dla potomnych. Najprawdopodobniej nieudało się pobrać plików binarnych z powodu braku zainstalowanej wtyczki do obsługi lfs.

Tutaj tutek:
https://github.com/git-lfs/git-lfs/wiki/Tutorial

Jeżeli to zadziałało to proszę o zamknięcie :)
